### ISSUE TITLE
atualizar links e-SIC

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/age7#1]
@gabrielbdornas por que [esse PR](https://github.com/transparencia-mg/age7/commit/34e493ffa7fce8a866b137ef4ad3309c46e7d800) não refletiu na atualização de 28/07?

**Comment by gabrielbdornas** [comment]
@Andrelamor vou fechar este issue por entender que já resolvermos a questão. O link não havia sido atualizado automaticamente pois a pull para o respositório na máquina da dti não estava sendo realizado. Em caso de dúvidas estou à disposição.
