### ISSUE TITLE
Validação de dados e metadados de um recurso específico

### ISSUE THREAD

**Issue by silviana-faria** [transparencia-mg/age7#112]
Atualmente não é possível  validar por meio do `make validate` apenas o recurso que está sendo alterado.

Por exemplo, ao realizar uma alteração no recurso _dm_favorecido_ e digitar na linha de comando `make validate`  a validação é acionada para todos os demais recursos do branch. Como alguns recursos contém várias informações as vezes esse processo torna-se bastante demorado.

**Comment by Andrelamor** [comment]
@fjuniorr @silviana-faria não existe outra forma de validar, colocando parâmetros junto com o comando ``make validate``, p. ex.?

**Comment by fjuniorr** [comment]
Também acho que o caminho é criar um novo target no Makefile que aceita um argumento e valida dados (eg. `make validate_data resource=resource_name`).

@Andrelamor acho que é uma boa tarefa pra você. [Aqui](https://github.com/frictionlessdata/frictionless-py/issues/221) tem uma indicação para validar um único recurso de um `datapackage.json` e você pode usar o target [validate_metadata](https://github.com/transparencia-mg/age7/blob/69b885e5af054a3d1e58946c68aeb50ac0778cc5/Makefile#L28) como modelo pra fazer o novo.

**Comment by Andrelamor** [comment]
@fjuniorr pensei num target tipo:
````
validate_data: ## Valida arquivo (usage: make validate_data resource=resource_name)
	@echo "Validando recurso $(resource)"
	@python scripts/validate-tableresource.py $(resource)
````
entretanto, o argumento `resource` do Makefile aponta para [um dos scripts em R](https://github.com/transparencia-mg/age7/blob/69b885e5af054a3d1e58946c68aeb50ac0778cc5/scripts/describe_resource.R)

já no `validate-tableresource.py`, pensei em algo do tipo

````
import sys
# from pathlib import Path, PurePath
from pprint import pprint
from datapackage import Package
from frictionless import validate_resource
from frictionless import validate_schema
from schema import Schema

def validate_tableresource (resource):
    package = Package('datapackage.json')
    for resource in package.resources:
        report = validate_resource(resource.source, schema)
        print(report)

if __name__ == '__main__':
   validate_tableresource(sys.argv[1])
```` 
mas não consegui achar alternativas para:
1. como substituir os pacotes `datapackage` e `schema` 
2. como achar referência de uma lista de "resources" para encaixar na estrutura de repetição/loop, a partir da função [validate-resource.py](https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/validate/resource.py)
3. como confrontar o recurso com o seu respectivo schema

**Comment by Andrelamor** [comment]
o uso da função no [último commit](https://github.com/transparencia-mg/age7/commit/d5f2665625b5150aa1862fa59d5281b4e423aba7) tentava confrontar o recurso com o schema, mas resultou no erro seguinte:
````
(age7) C:\Users\Andre\Documents\teletrabalho\transparencia-mg\age7>python scripts/resource_validation.py "dm_unidade_orc"
Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\site-packages\datapackage\helpers.py", line 145, in dereference_resource_descriptor
    descriptor[property] = json.load(file)
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Andre\Documents\teletrabalho\transparencia-mg\age7\scripts\resource_validation.py", line 14, in <module>
    resource_validation(sys.argv[1])
  File "C:\Users\Andre\Documents\teletrabalho\transparencia-mg\age7\scripts\resource_validation.py", line 8, in resource_validation
    package = Package('datapackage.json')
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\site-packages\datapackage\package.py", line 103, in __init__
    descriptor = helpers.dereference_package_descriptor(descriptor, base_path)
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\site-packages\datapackage\helpers.py", line 87, in dereference_package_descriptor
    dereference_resource_descriptor(resource, base_path, descriptor)
  File "C:\Users\Andre\AppData\Local\R-MINI~1\envs\age7\lib\site-packages\datapackage\helpers.py", line 148, in dereference_resource_descriptor
    six.raise_from(
  File "<string>", line 3, in raise_from
datapackage.exceptions.DataPackageException: Not resolved Local URI "schemas/dm-unidade-orc.yaml" for resource.schema````

parece que a função não tem comando para ler o formato `yaml` como a linha abaixo comenta, na função `validate-tableschema.py`:
````
def validate_tableschema(schema):
    #filename = Path("schemas", PurePath(resource).with_suffix('.yaml'))
    report = validate_schema(schema)
    pprint(report)
````

**Comment by fjuniorr** [comment]
@Andrelamor usando o `frictionless` no lugar do `goodtables` a validaçao deve funcionar. Ou seja, substituir 

```
from datapackage import Package
from goodtables import validate
```

por

```
from frictionless import Package
from frictionless import validate
```

Você chegou a testar isso?

**Comment by Andrelamor** [comment]
parece estar faltando um parâmetro, o [`resource.source`](https://github.com/frictionlessdata/frictionless-py/blob/02532f6b1c2796faf5ff57e6284c642f9ece6ea6/frictionless/validate/resource.py#L32):

````
(age7) C:\Users\Andre\Documents\teletrabalho\transparencia-mg\age7>python scripts/validate-tableresource.py dm-acao
Traceback (most recent call last):
  File "C:\Users\Andre\Documents\teletrabalho\transparencia-mg\age7\scripts\validate-tableresource.py", line 21, in <module>
    validate_tableresource(sys.argv[1])
  File "C:\Users\Andre\Documents\teletrabalho\transparencia-mg\age7\scripts\validate-tableresource.py", line 11, in validate_tableresource
    report = validate_resource(resource.source, schema)
AttributeError: 'Resource' object has no attribute 'source'
````
na [documentação](https://specs.frictionlessdata.io/data-package/#sources), `source` pode ser a URL ou o caminho relativo; mesmo colocando o segundo como novo argumento da função, o erro é o mesmo

**Comment by Andrelamor** [comment]
@gabrielbdornas na minha última tentativa com a [função acima](), o novo datapackage criado não capturou o esquema do recurso passado como argumento da função:

**Comment by fjuniorr** [comment]
@Andrelamor com o snippet abaixo a validação funciona para arquivos yaml:

```python
from frictionless import Package
from frictionless import validate_resource, validate

package = Package('https://raw.githubusercontent.com/dados-mg/datapackage-reprex/limit-rows/datapackage.json')
resource_name = 'pib-per-capita'
resource = package.get_resource(resource_name)
report = validate_resource(resource) # validate(resource) também funciona
report.flatten(['code', 'message'])
# [['foreign-key-error',  'Row at position "1500" violates the foreign key: not found in the lookup table']]
```

Também confirmei que usando a linha de comando as restrições de chaves estrangeiras não são validadas

```bash
frictionless validate --schema https://raw.githubusercontent.com/dados-mg/datapackage-reprex/limit-rows/schemas/pib-per-capita.yaml https://raw.githubusercontent.com/dados-mg/datapackage-reprex/limit-rows/data/pib-per-capita.csv 
# -----
# valid: https://raw.githubusercontent.com/dados-mg/datapackage-reprex/limit-rows/data/pib-per-capita.csv
# -----
```

O problema [nesse snippet](https://github.com/transparencia-mg/age7/commit/d5f2665625b5150aa1862fa59d5281b4e423aba7#diff-244f516b675d6876615d203c365d287ac657d5d6f1d7a9d3134f43ce9726322cR4-R11) na linha `validate(resource.source, schema=resource.schema.descriptor)` deve ser por alterações entre os argumentos da função na migração entre `goodtables.py` e `frictionless.py`.


Lembro que o @gabrielbdornas tinha falado que também teve um problema de controlar o número de linhas validadas. Ainda não consegui descobrir como controlar isso (a chave parece ser com o argumento [limit_rows](https://framework.frictionlessdata.io/docs/references/api-reference/#layoutlimit_rows)), mas nos testes que fiz isso não foi um problema. 

Amanhã implemento o resto do script.
