### ISSUE TITLE
Tabela DM_FAVORECIDO ausente nos 2 dumps

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/age7#122]
Embora prevista no [schema](https://github.com/transparencia-mg/age7/blob/main/schemas/dm-favorecido.yaml), a tabela dm-favorecido não apareceu no [repo](https://github.com/transparencia-mg/age7/commit/6087ec826ad2b0d51eadfe79bb9b7f5c23d1e641) em nenhum dos 2 dumps

**Comment by fjuniorr** [comment]
Tabela não foi subida para o Github em virtude da presença de dados pessoais
