### ISSUE TITLE
Erro tabela dm_fonte

### ISSUE THREAD

**Issue by silvianafaria** [transparencia-mg/age7#156]
Erro: 
As [tabela dm_fonte_rec] e [dm_fonte] indica que existem novas fontes que não constam na documentação.

![image](https://user-images.githubusercontent.com/53793354/204810025-d91ee2cf-66f4-480e-82a3-cac30807870a.png)

![image](https://user-images.githubusercontent.com/53793354/204816589-eec98584-0e44-4da7-a97e-dc9685976a8a.png)

Considerações:

1- Fonte 18 : Criada em 09/09/2022 - [Classificador da Despesa ](https://docs.google.com/document/d/1N6YsGC5vQi-CA2Hx1vevw3gVRFWJZ4uS/edit#heading=h.434ayfz)
![image](https://user-images.githubusercontent.com/53793354/204810247-be62fa50-72ac-476c-91ca-b9fd6d54bab5.png)

2- As demais fontes não foram localizadas nas tabelas do armazém de dados BO. 
![image](https://user-images.githubusercontent.com/53793354/204816927-dd042af9-c849-4520-bed2-5e2df6f58139.png)

Solução:

1- Acrescentar a código da fonte 18 nas tabelas [tabela dm_fonte_rec] e [dm_fonte] 
"constraints": {
              "enum": [
![image](https://user-images.githubusercontent.com/53793354/204817152-cb6eb677-af70-40f3-80ae-e0c365065388.png)

2- Acrescentar os códigos 2, 9 e 15 nas tabelas [tabela dm_fonte_rec] e [dm_fonte] no campo "cd_fonte"
             "missingValues": [
              "0"

![image](https://user-images.githubusercontent.com/53793354/204817711-7a1a7da3-06d1-4874-9da2-f80ee8bcfde9.png)

**Comment by silvianafaria** [comment]
@kesiabomfa 

1 - Acrescentar o código da fonte 18 na tabela ft_receita_prevista_v2018 nos 
"constraints": {
"enum": [


2- Acrescentas pps códigos das fontes 5, 65. 2, 66, 3, 64, 68, 6, 9, 2 na tabela dm_fonte_orcam
"missingValues": [
"0"

**Comment by kesiabomfa** [comment]
finalizado
