### ISSUE TITLE
erro validação tabela  dm-tipo-orcam-plan

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/age7#178]
````
schema-error  Schema is not valid: cannot extract metadata "schemas/dm-tipo-orcam-plan.yaml" because
"while parsing a block mapping
  in "<file>", line 10, column 5
expected <block end>, but found '<block mapping start>'
  in "<file>", line 25, column 7"
````
![image](https://user-images.githubusercontent.com/52294411/134533585-78753e8f-70af-468d-804d-6934daac5247.png)

![image](https://user-images.githubusercontent.com/52294411/134533730-c35c7da0-6e55-4fb8-8528-8ad7c0aaf7fb.png)

**Comment by fjuniorr** [comment]
Os novos testes de validação serão feitos com os dados extraídos da replicação no MySQL da Kyoto.
