### ISSUE TITLE
erro validação tabela dm-decreto

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/age7#179]
````
===============================================================================
 244      3  constraint-error  The cell "9999999" in row at position "244" and field "nr_decreto" at
position "3" does not conform to a constraint: constraint "required" is "True"
````
'9999999' claramente não é um número válido de um decreto, parece ter sido digitado na tabela para valores ausentes:
![image](https://user-images.githubusercontent.com/52294411/134534766-37d0a198-879c-4e8e-a80a-bb7239a6333f.png)
mas '9999999' não pode ser atribuído como `missingValues` pois esse campo só aceita string : https://specs.frictionlessdata.io/table-schema/#missing-values

**Comment by fjuniorr** [comment]
Os novos testes de validação serão feitos com os dados extraídos da replicação no MySQL da Kyoto.
