### ISSUE TITLE
erro validação tabela fl-convenio-alteracao

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/age7#180]
````
==========  ======================================
code        message
==========  ======================================
task-error  The task has an error: 'fieldPosition'
==========  ======================================
````
a tabela está com campos fora do padrão do `schema`, parece ter sido erro no processo de geração da tabela original:

![image](https://user-images.githubusercontent.com/52294411/134535897-62b1d752-12c7-498f-80b0-501a95a588f4.png)

**Comment by fjuniorr** [comment]
Os novos testes de validação serão feitos com os dados extraídos da replicação no MySQL da Kyoto.
