### ISSUE TITLE
erro validação foreign key tabela ft-convenio-entrada-desp

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/age7#181]
````
code          message


============  ===============================================================================================================================================================================================================================================================
schema-error  Schema is not valid: "{'fields': ['id_favorecido'], 'reference': {'fields': ['id_favorecido']}, 'resource': 'dm_favorecido'} is not valid under any of the given schemas" at "foreignKeys/4" in metadata and at "properties/foreignKeys/items/oneOf" in profile
````

* Contexto:

a tabela `dm_favorecido` ainda [não foi adicionada ao repositório](https://github.com/transparencia-mg/age7/tree/main/data), provavelmente para anonimização de dados pessoais de beneficiários da despesa

*  trecho do [schema da tabela `ft-convenio-entrada-desp`](https://github.com/transparencia-mg/age7/blob/main/schemas/ft-convenio-entrada-desp.yaml) que faz referência à chave estrangeira da tabela dm-favorecido:

````
  - fields:
  - id_favorecido
    reference:
      fields:
      - id_favorecido
    resource: dm_favorecido
````

**Comment by fjuniorr** [comment]
Os novos testes de validação serão feitos com os dados extraídos da replicação no MySQL da Kyoto.
