### ISSUE TITLE
Makefile não seguindo a ordem dos comando em `make all`

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/age7#199]
Ao executar `make all` (all: parse extract ingest validate notify), erro:

```
rsync: link_stat "/vagrant/data/raw/*" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
rsync: link_stat "/vagrant/data/raw/*" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Rscript --verbose scripts/r/parse-sql.R ft_receita_v2018 2> logs/parse/ft_receita_v2018.Rout
Rscript --verbose scripts/r/parse-sql.R dm_unidade_orc 2> logs/parse/dm_unidade_orc.Rout
Rscript --verbose scripts/r/parse-sql.R ft_convenio_entrada 2> logs/parse/ft_convenio_entrada.Rout
python scripts/python/extract-resource.py ft_receita_v2018 2> logs/extract/ft_receita_v2018.txt
python scripts/python/extract-resource.py dm_unidade_orc 2> logs/extract/dm_unidade_orc.txt
python scripts/python/extract-resource.py ft_convenio_entrada 2> logs/extract/ft_convenio_entrada.txt
make: *** No rule to make target 'data/ft_receita_v2018.csv.gz', needed by 'logs/validate/ft_receita_v2018.json'.  Stop.
```

Parte final do erro `No rule to make target 'data/ft_receita_v2018.csv.gz', needed by 'logs/validate/ft_receita_v2018.json` é um indicativo de que a validação está sendo executada antes do ingest.

[Este post](https://stackoverflow.com/a/45702209/11755155) sugere incluir um "|" no início do comando, mas tentativa não funcionou

Já [esta resposta](https://stackoverflow.com/a/9160163/11755155) indica que a ordem de execução é definida pela listagem dos prerequisitos. Acredito que algum prerrequisito da função "validate" está vindo antes da função ingest

**Comment by fjuniorr** [comment]
A gente ainda precisa fazer uma depuração da lógica do makefile numa sessão de programação em pares (transparencia-mg/age7#202) e construir uma visualização das dependências (transparencia-mg/age7#201). Mas, dado ao adiantado da hora, a maior lição dessas respostas é:

> But ideally, you should design your Makefiles so that it wouldn't rely on the order in which prerequisites are specified. That is, if y should be executed after z, there must be a y : z dependence.

Pra forçar uma execução sequencial e agendar no cron podemos usar uma [lista AND de comandos](https://www.gnu.org/software/bash/manual/html_node/Lists.html) (ie. `&&`)

```
make parse && make extract && make ingest && make validate && make datapackage.json
make: Nothing to be done for 'parse'.
make: Nothing to be done for 'extract'.
make: Nothing to be done for 'ingest'.
make: Nothing to be done for 'validate'.
make: 'datapackage.json' is up to date.
```

Ainda precisamos inserir nessa lista os targets finais de construir os data packages derivados e fazer upload para o CKAN.

**Comment by fjuniorr** [comment]
Resolvido com arquivo `all.sh`
