### ISSUE TITLE
dtamg-py como estratégia para migração dos scripts em etl-make

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#216]
Copiar e colar os scripts não é uma estratégia interessante pois vamos precisar de manter o código em dois lugares.

Desenvolver somente no repo `age7` não é interessante porque ele é muito grande, tornando o teste das modificações muito custoso.

Uma estratégia é criar um pacote interno `dtamg-py`. Os scripts `scripts/python/utils.py` viram funções e os scripts chamados nos targets do Makefile viram comandos na linha de comando (eg. `dta full-extract`).

**Comment by gabrielbdornas** [comment]
@fjuniorr, pacote [dtamg-py](https://github.com/transparencia-mg/dtamg-py) criado com sucesso. Arquivo Makefile do [repositório etl-make](https://github.com/dados-mg/etl-make) também [refatorado](https://github.com/dados-mg/etl-make/tree/72d782710a6d43c91556ac0e7ae84e4a5b81d4c9) para receber as modificações. Acredito que para fecharmos o issue bastará realizarmos os testes e migrar este arquivo Makefile para o repositório [age7](https://github.com/transparencia-mg/age7). O que acha?

**Comment by fjuniorr** [comment]
Issue finalizado. 

Melhorias viram issues específicos.
