### ISSUE TITLE
Update dpckan version

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/age7#22]
@fjuniorr, dpckan version in the project is pretty old, as we can see below:

https://github.com/transparencia-mg/age7/blob/faea2837a7bc724ada9935bc874c32675a7ec7f6/requirements.txt#L1

Corrections like dataset update are present in [dpckan new version](https://pypi.org/project/dpckan/).

**Comment by gabrielbdornas** [comment]
[Update here](https://github.com/transparencia-mg/docker-age7/blob/main/requirements.txt), but before see:

- #131 
- #10

**Comment by Andrelamor** [comment]
@gabrielbdornas os erros que vimos hoje:

1. retomar a versão mais recente da frictionless em vez de fixá-la
2. mensagem de já haver um dataset com mesmo nome na organização (ainda incerto se é com o `dpckan`):
````
$ dpckan --datastore --ckan-host $HOMOLOGA_HOST --ckan-key $HOMOLOGA_KEY dataset create
Creating dataset https://homologa.cge.mg.gov.br/dataset/violencia-contra-m
ulher
secretaria-de-estado-de-justica-e-seguranca-publica-sejusp, not exist in h
ttps://homologa.cge.mg.gov.br/dataset/violencia-contra-mulher
````
tentei mudar o nome do conjunto novamente, e aparece a mesma msg:
````
$ dpckan --datastore --ckan-host $HOMOLOGA_HOST --ckan-key $HOMOLOGA_KEY dataset create
Creating dataset https://homologa.cge.mg.gov.br/dataset/violencia-cont
ra-a-mulher
secretaria-de-estado-de-justica-e-seguranca-publica-sejusp, not exist
in https://homologa.cge.mg.gov.br/dataset/violencia-contra-a-mulher
````



### OBS.: hipótese descartada:
acho que a exclusão definitiva para o CKAN entender que não existe outro dataset ativo com mesmo nome será via `purge` do usuário sysadmin da DTI:
![image](https://user-images.githubusercontent.com/52294411/218820264-b6bf9e3d-4419-4baf-9708-fa9adf927235.png)

**Comment by gabrielbdornas** [comment]
Finalizado [aqui](https://github.com/transparencia-mg/dpckan/tree/v0.1.20).
