### ISSUE TITLE
Explorar flags `--ignore-errors` e `--keep-going` do make

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#226]
A natureza desse issue está ligada ao fato de que ao executar, por exemplo, um `make validate`, pode ser bom que mesmo que na primeira validação um erro seja lançado, os demais recursos ainda sejam validados durante e execução atual.

Ainda é preciso avaliar as consequencias nos processos seguintes. No caso da validação, por exemplo, com os scripts atuais, o arquivo `datapackage.json` não é criado, a menos que todos os logs existam em `logs/validate/*.json`.

Esse comportamento pode ser bom em todos os casos em que cada ação demora muito para ser executada (eg. `dpckan update`)

**Comment by gabrielbdornas** [comment]
@fjuniorr, conforme sugerido [neste post](https://stackoverflow.com/a/53039783/11755155) a flag "--ignore-errors" ou "-i" pode ser utilizada para evitar interrupções no fluxo de comandos Make em caso de erros. Ela continua imprimindo o motivo de erro (o que será importante para futuras correções), mas passando status de sucesso para as próximas execuções. Escrever um hifem "-" ao início da execução do comando desempenha o mesmo papel da flag em questão. Por exemplo:

```
clean:
        -rm -f *.o
```

A flag "--keep-going" ou "k", por outro lado, precisa do retorno de erro para funcionar corretamente. Ele entenderá que o arquivo dependente final não será criado, mas construirá tantos forem possíveis. Pode ser útil para encontrar problemas. Não é possível utilizar as duas flags juntas porque "-i" retornará o status de sucesso e "k" precisa de erros para ser acionada.

Por que comandos make sequenciais param em caso de erro? Porque o Make entende que se o target atual não pode ser construído seus dependentes também não poderão.

**Comment by gabrielbdornas** [comment]
@fjuniorr, podemos fechar o issue?
