### ISSUE TITLE
Alterar todos os table schema para extrair colunas anonimizadas do banco de dados MySQL

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#228]
A coluna `col_name` anonimizada vai estar disponível como `col_name_anonimizado`.

Lembrar que os recursos `dm_empenho_desp_compras_empenho` e `dm_empenho_desp_diarias_scdp_liqpag` também precisam ser alterados pois usam como fonte a `dm_empenho_desp`.

**Comment by gabrielbdornas** [comment]
Não fiz a troca das tabelas dm_empenho_resto_* porque em 20/12/2021 o campo razao_social_credor_anonimizado ainda não havia sido incluído na tabela
