### ISSUE TITLE
Remover extended do nome do arquivo extended_datapackage.json

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#232]
https://homologa.cge.mg.gov.br/dataset/fadeb64b-25d2-417a-8e5e-2b3689ded17e/resource/194daf8f-9328-4e22-987e-9459d5c803c4/download/extended_datapackage.json

**Comment by gabrielbdornas** [comment]
Finalizado após [este commit](https://github.com/dados-mg/dpckan/tree/v0.1.13)
