### ISSUE TITLE
dm_contratado não possui coluna nr_documento_anonimizado

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#237]
A coluna nr_documento também não está anonimizada

**Comment by gabrielbdornas** [comment]
@fjuniorr erro meu, tinha entendido que este campo retornaria apenas CNPJs, mas em conversa com @silviana-faria ela me explicou que em algumas situações CNPJ pode ser cadastrado no campo nr_documento e CPF incluído no campo nome (MEI) e que pode sim haver situações aonde apenas CPF é cadastrado nos dois campos. Este filtro poderá ser feito através do campo tp_documento. Sendo assim, tp_documento = 1 deverão apresentar campo nr_documento anonimizado.

Neste sentido, pedirei Márcia para incluir o script abaixo na consulta anteriormente encaminhada

```
CASE WHEN dc.tp_documento = 1 THEN
    '***' || SUBSTR(dc.nr_documento, 4, 6) || '**' END nr_documento_anonimizado,
```

**Comment by gabrielbdornas** [comment]
@fjuniorr finalizado [aqui](https://github.com/transparencia-mg/dtamg-r/tree/v0.2.4), favor atualizar a versão do pacote dtmag-r `remotes::install_github('transparencia-mg/dtamg-r@v0.2.4')` para testar.
