### ISSUE TITLE
Criar índices no banco MySQL da Kyoto

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#238]

**Comment by gabrielbdornas** [comment]
@fjuniorr, podemos fechar os issue?

**Comment by fjuniorr** [comment]
Foram criados índices em todas as colunas utilizadas em clausulas WHERE e que ainda não possuiam índice, quais sejam:
 
- dm_empenho_desp.ano_exercicio
- dm_empenho_desp.id_empenho
- ft_diarias_scdp_liqpag.id_empenho
- dm_empenho_resto.ano_exercicio
- ft_diarias.ano_particao
- ft_restos_pagar.ano_particao
