### ISSUE TITLE
Erro (a ?)  no campo descrição do recurso

### ISSUE THREAD

**Issue by silviana-faria** [transparencia-mg/age7#24]
Verificar se o erro de codificação apresentado na descrição dos recursos foi ocasionado no momento da extração dos dados pela DTA ou se é originário da base.

[dm_fonte_rec/data](https://github.com/transparencia-mg/age7/blob/dm_fonte_rec/data/dm-fonte-rec.csv.gz)
![image](https://user-images.githubusercontent.com/53793354/125674584-2da8189a-b2c2-49ff-bf18-5ce4b8ab2961.png)

**Comment by fjuniorr** [comment]
Acho que problema está acontecendo na hora da extração para gerar o arquivo `csv` (feito via R). Consultando no banco de dados via SQL Developer eu vejo

![Oracle_SQL_Developer___Table_AGE7_DM_FONTE_REC_AGE7_19c](https://user-images.githubusercontent.com/4969445/127044176-6888221e-6e03-4d57-8d29-990538ce75b6.png)

O recurso `dm_documento_viagem` é outro exemplo de texto com muito acento que pode ser usado pra investigação.

Além disso, encontrei outros problemas relacionados a acentuação mas diferentes.

O primeiro deles é que parece que nem todos os acentos geram erro, alguns são simplesmente removidos. Vide diferença da visão do SQL Developer e do csv para o recurso `dm_estado`

![Oracle_SQL_Developer___Table_AGE7_DM_ESTADO_AGE7_19c](https://user-images.githubusercontent.com/4969445/127044627-84f85b96-d0d0-4842-865b-9822dd8c0b63.png)

```
id_estado;sqe_estado;nome
1;0;-
2;1;ACRE
3;2;ALAGOAS
4;3;AMAZONAS
5;4;AMAPA # exemplo acento removido
6;5;BAHIA
7;6;CEARA
8;7;DISTRITO FEDERAL
9;8;ESPIRITO SANTO
10;9;GOIAS
11;10;MARANH?O # erro
12;11;MINAS GERAIS
13;12;MATO GROSSO DO SUL
14;13;MATO GROSSO
15;14;PARA
16;15;PARAIBA # exemplo acento removido
17;16;PERNAMBUCO
18;17;PIAUI
19;18;PARANA
20;19;RIO DE JANEIRO
21;20;RIO GRANDE DO NORTE
22;21;RONDONIA
23;22;RORAIMA
24;23;RIO GRANDE DO SUL
25;24;SANTA CATARINA
26;25;SERGIPE
27;26;S?O PAULO # erro
28;27;TOCANTINS
```

Além disso, ainda no recurso `dm_fonte_rec`, parece que alguns caracteres com acentos foram completamente removidos:

![Oracle_SQL_Developer___Table_AGE7_DM_FONTE_REC_AGE7_19c](https://user-images.githubusercontent.com/4969445/127046580-2001aea8-9a15-4957-91e9-a94e7c58359b.png)

**Comment by fjuniorr** [comment]
Essas duas perguntas são relevantes

- [Encoding in ROracle](https://stackoverflow.com/questions/50366322/encoding-in-roracle)
- [ROracle encoding issues](https://stackoverflow.com/questions/46807009/roracle-encoding-issues)

**Comment by fjuniorr** [comment]
Novos issues serão criados a medida em que problemas de mojibake foram aparecendo.
