### ISSUE TITLE
Criar índices na VM Kyoto hospedada na infra CGE

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#272]
Vide #238. Necessário avaliar se de fato todas as colunas estão especificadas no issue #238.

**Comment by gabrielbdornas** [comment]
@fjuniorr, segundo informações repassadas por Fernando em nosso grupo do Teans (13/05/2022 às 2:52), todos os índices foram replicados na nova estrutura da CGE:

![image](https://user-images.githubusercontent.com/49699290/168340693-bf22418e-c248-4c71-a915-a6048c9bc0c7.png)

Sendo assim, fecharei o issue.
