### ISSUE TITLE
Erros de validação recorrentes

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/age7#76]
Desde o início da execução do fluxo de ETL temos tidos erros de validação no `make validate`. Dos 206 recursos, o menor número de erros foi de 20 na execução de 28/12/2021. Desde então esse número tem se mantido de torno de 55 em jan/2022.

Por causa de problemas como o relatado em transparencia-mg/new-age7#79, a investigação e resolução dos problemas é custosa, mas precisa ser feita.

Macro ações:

- [ ] Correção [mantis #164334](https://www.mantis.prodemge.gov.br/view.php?id=164334)
- [x] Ajuste horário das cargas
- [x] Conferência erros de integridade referencial
- [x] Criação de relatório online

**Comment by gabrielbdornas** [comment]
[Mantis #164334](https://www.mantis.prodemge.gov.br/view.php?id=164334) corrigido.

![image](https://user-images.githubusercontent.com/49699290/201094190-12656f14-3fe9-42df-85a5-4254028a1311.png)
